# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

StatRead_cpp <- function(sample, readfile, Type = NULL) {
    .Call('_rfastqQC_StatRead_cpp', PACKAGE = 'rfastqQC', sample, readfile, Type)
}

